### ISSUE TITLE
{read: false} on examples

### ISSUE THREAD

**Issue by keit** [moneypenny/gulp-ruby-haml#15]
Hi, 
I am very new to gulp so this might be a stupid question but what is the reason 'read: false' on example?
With the option, the task does not write out html files...

**Comment by moneypenny** [comment]
See the Gulp-inject section in http://denbuzze.com/post/5-lessons-learned-using-gulpjs/ The `read: false` is an option passed to `gulp.src` and isn't particular to the gulp-ruby-haml plugin. We don't need gulp to read the haml files because the `haml` command-line script will do that.
